name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --logger "junit;LogFilePath=tests.xml"
    - name: Test Summary
      uses: test-summary/action@v1
      with:
          output: summary.md
          paths: ./**/*.xml
      if: always()
    - name: Upload test summary
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{github.run_number}}.md
        path: summary.md
      if: always()